SHARING_OPTION_PUBLIC = 'PUBLIC'
SHARING_OPTION_INVITE = 'INVITEONLY'
SHARING_OPTION_PRIVATE = 'PRIVATE'

SHARING_CHOICES = (
    (SHARING_OPTION_PUBLIC, 'Members'),
    (SHARING_OPTION_INVITE, 'By Invitation Only'),
    (SHARING_OPTION_PRIVATE, 'Private / Full Flight')
)
